language: node_js
node_js:
  - "9" # Current
  - "8" # LTS (Active)
  - "6" # LTS (Active)
  - "4" # LTS (Maintenance)

os:
  - linux

branches:
  only:
    - master
    - /^greenkeeper/.*$/

notifications:
  email: false
